name: Update Strava Activities

on:
  schedule:
    - cron: '0 19 * * *'
  workflow_dispatch:

jobs:
  update-page:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Fetch Strava Activities and Update Page
        run: |
          python update_page_with_activities.py
