name: Update Strava Activities

on:
  schedule:
    - cron: '0 19 * * *'
  workflow_dispatch:

jobs:
  update-page:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r "./dashboard/requirements.txt"

      - name: Fetch Strava Activities and Update Page
        env:
          STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
          STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
          STRAVA_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}
        run: |
          python ./dashboard/update_page_with_activities.py

      - name: Check for changes
        id: git-status
        run: |
          git status --porcelain
          echo "::set-output name=status::$(git status --porcelain)"

      - name: Commit and push changes
        if: steps.git-status.outputs.status != ''
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions Bot"
          git add .
          git commit -m "Update activities from Strava"
          git push
